CREATE TABLE IF NOT EXISTS users (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      TEXT NOT NULL UNIQUE,
  email         TEXT NOT NULL UNIQUE,
  password_hash TEXT,
  google_id     TEXT UNIQUE,
  avatar_url    TEXT,
  full_name     TEXT,
  bio           TEXT,
  location      TEXT,
  website       TEXT,
  role          TEXT NOT NULL DEFAULT 'USER',
  rating        INTEGER NOT NULL DEFAULT 1200,
  theme         TEXT NOT NULL DEFAULT 'dark',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token       TEXT NOT NULL UNIQUE,
  expires_at  TIMESTAMPTZ NOT NULL,
  revoked     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_refresh_user ON refresh_tokens(user_id);

CREATE TABLE IF NOT EXISTS categories (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug        TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  description TEXT,
  icon        TEXT,
  color       TEXT
);

CREATE TABLE IF NOT EXISTS problems (
  id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug                  TEXT NOT NULL UNIQUE,
  title                 TEXT NOT NULL,
  description           TEXT NOT NULL,
  difficulty            TEXT NOT NULL DEFAULT 'EASY',
  problem_type          TEXT NOT NULL DEFAULT 'ALGORITHM',
  category_id           INTEGER REFERENCES categories(id),
  tags                  TEXT,
  examples_json         TEXT,
  constraints           TEXT,
  hints_json            TEXT,
  starter_code_json     TEXT,
  expected_output       TEXT,
  test_cases_json       TEXT,
  sql_setup             TEXT,
  function_name         TEXT,
  time_limit_ms         INTEGER NOT NULL DEFAULT 1000,
  memory_limit_mb       INTEGER NOT NULL DEFAULT 256,
  is_premium            BOOLEAN NOT NULL DEFAULT FALSE,
  total_submissions     INTEGER NOT NULL DEFAULT 0,
  accepted_submissions  INTEGER NOT NULL DEFAULT 0,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_problems_difficulty ON problems(difficulty);
CREATE INDEX IF NOT EXISTS idx_problems_category ON problems(category_id);
CREATE INDEX IF NOT EXISTS idx_problems_type ON problems(problem_type);

CREATE TABLE IF NOT EXISTS submissions (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  problem_id    INTEGER NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
  language      TEXT NOT NULL,
  code          TEXT NOT NULL,
  status        TEXT NOT NULL,
  runtime_ms    INTEGER,
  memory_kb     INTEGER,
  tests_passed  INTEGER,
  tests_total   INTEGER,
  output        TEXT,
  error         TEXT,
  beats_pct     DOUBLE PRECISION,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_submissions_user ON submissions(user_id);
CREATE INDEX IF NOT EXISTS idx_submissions_problem ON submissions(problem_id);
CREATE INDEX IF NOT EXISTS idx_submissions_status ON submissions(status);

CREATE TABLE IF NOT EXISTS favorites (
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  problem_id INTEGER NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, problem_id)
);

CREATE TABLE IF NOT EXISTS oauth_states (
  state      TEXT PRIMARY KEY,
  redirect   TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
