-- 0003_courses.sql
-- Phase 1 #3: courses + the course_problems link table.
--
-- Per ADR 0007:
--   - `courses` is owned by exactly one user (an INSTRUCTOR or ADMIN).
--   - Default REFERENCES action is NO ACTION, so a user that owns a
--     course cannot be deleted until ownership is reassigned. This is
--     deliberate — see ADR §"Foreign-key behaviour".
--   - `course_problems` is the syllabus link table. Both sides cascade
--     on delete because the link is meaningless without either end.
--   - `position` is intentionally non-unique and 0-default; canonical
--     sort is `(position ASC, added_at ASC, problem_id ASC)`.

CREATE TABLE IF NOT EXISTS courses (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug        TEXT NOT NULL UNIQUE,
  title       TEXT NOT NULL,
  description TEXT,
  owner_id    INTEGER NOT NULL REFERENCES users(id),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_courses_owner ON courses(owner_id);

CREATE TABLE IF NOT EXISTS course_problems (
  course_id  INTEGER NOT NULL REFERENCES courses(id)  ON DELETE CASCADE,
  problem_id INTEGER NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
  position   INTEGER NOT NULL DEFAULT 0,
  added_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (course_id, problem_id)
);
CREATE INDEX IF NOT EXISTS idx_course_problems_problem ON course_problems(problem_id);
