-- 0004_groups.sql
-- Phase 1 #4: cohorts (groups) inside a course + their member enrolment.
--
-- Per ADR 0008:
--   - `groups.slug` is unique PER COURSE (not globally) so two courses
--     can both have a "section-a".
--   - Deleting a course or a user cascades through enrolment. The course
--     owner is still protected from deletion by the FK on
--     `courses.owner_id` from ADR 0007.
--   - `group_members` is a pure link table; no per-row metadata beyond
--     `joined_at`. Per-group roles (TA, etc.) are an explicit non-goal.

CREATE TABLE IF NOT EXISTS groups (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id   INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  slug        TEXT NOT NULL,
  title       TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (course_id, slug)
);
CREATE INDEX IF NOT EXISTS idx_groups_course ON groups(course_id);

CREATE TABLE IF NOT EXISTS group_members (
  group_id   INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  user_id    INTEGER NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
  joined_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (group_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_group_members_user ON group_members(user_id);
