-- 0005_exams.sql
-- Phase 1 #5: timed exams + attempts + link into the existing submissions
-- table. Per ADR 0009:
--   - `exams.group_id NULL` means the exam is open to every student
--     enrolled in the course (via any group).
--   - UNIQUE (course_id, slug) makes exam slugs unique per course, not
--     globally. CHECK constraints enforce "end > start" and positive
--     duration at the DB level.
--   - `submissions.exam_attempt_id` is nullable and ON DELETE SET NULL
--     so a submission survives the removal of the attempt it came from.

CREATE TABLE IF NOT EXISTS exams (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id         INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  group_id          INTEGER REFERENCES groups(id) ON DELETE CASCADE,
  slug              TEXT NOT NULL,
  title             TEXT NOT NULL,
  description       TEXT,
  starts_at         TIMESTAMPTZ NOT NULL,
  ends_at           TIMESTAMPTZ NOT NULL,
  duration_minutes  INTEGER NOT NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (course_id, slug),
  CHECK (ends_at > starts_at),
  CHECK (duration_minutes > 0)
);
CREATE INDEX IF NOT EXISTS idx_exams_course ON exams(course_id);
CREATE INDEX IF NOT EXISTS idx_exams_group  ON exams(group_id);

CREATE TABLE IF NOT EXISTS exam_problems (
  exam_id    INTEGER NOT NULL REFERENCES exams(id)    ON DELETE CASCADE,
  problem_id INTEGER NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
  position   INTEGER NOT NULL DEFAULT 0,
  points     INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (exam_id, problem_id),
  CHECK (points > 0)
);
CREATE INDEX IF NOT EXISTS idx_exam_problems_problem ON exam_problems(problem_id);

CREATE TABLE IF NOT EXISTS exam_attempts (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_id      INTEGER NOT NULL REFERENCES exams(id)  ON DELETE CASCADE,
  user_id      INTEGER NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
  started_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  finished_at  TIMESTAMPTZ,
  UNIQUE (exam_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_exam_attempts_user ON exam_attempts(user_id);

-- Link a submission back to the attempt it was made within. NULL for
-- regular (out-of-exam) practice submissions.
ALTER TABLE submissions
  ADD COLUMN IF NOT EXISTS exam_attempt_id INTEGER
    REFERENCES exam_attempts(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_submissions_exam_attempt ON submissions(exam_attempt_id);
