-- 0006_audit_events.sql
-- Phase 1 #8: installation-level audit log for privileged mutations.
-- Snapshot actor username/role at write time so the log remains readable
-- even if the user later changes role or is removed.

CREATE TABLE IF NOT EXISTS audit_events (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id        INTEGER REFERENCES users(id) ON DELETE SET NULL,
  actor_username  TEXT NOT NULL,
  actor_role      TEXT NOT NULL,
  action          TEXT NOT NULL,
  entity_type     TEXT NOT NULL,
  entity_key      TEXT NOT NULL,
  details_json    JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_events_created_at
  ON audit_events(created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_audit_events_action
  ON audit_events(action);
CREATE INDEX IF NOT EXISTS idx_audit_events_entity_type
  ON audit_events(entity_type);
CREATE INDEX IF NOT EXISTS idx_audit_events_actor_username
  ON audit_events(actor_username);
