-- 0009_contests.sql
-- Contest mode: university-wide competitive-programming events with
-- ICPC scoring, frozen standings, virtual participation, and Glicko-2 rating.

CREATE TABLE IF NOT EXISTS contests (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug            TEXT NOT NULL UNIQUE,
  title           TEXT NOT NULL,
  description     TEXT,
  starts_at       TIMESTAMPTZ NOT NULL,
  ends_at         TIMESTAMPTZ NOT NULL,
  freeze_minutes  INTEGER NOT NULL DEFAULT 30,
  is_public       BOOLEAN NOT NULL DEFAULT true,
  editorial       TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (ends_at > starts_at),
  CHECK (freeze_minutes >= 0)
);

CREATE TABLE IF NOT EXISTS contest_problems (
  contest_id  INTEGER NOT NULL REFERENCES contests(id) ON DELETE CASCADE,
  problem_id  INTEGER NOT NULL REFERENCES problems(id) ON DELETE RESTRICT,
  letter      TEXT NOT NULL,
  PRIMARY KEY (contest_id, problem_id),
  UNIQUE (contest_id, letter),
  CHECK (letter ~ '^[A-Z]$')
);
CREATE INDEX IF NOT EXISTS idx_contest_problems_problem ON contest_problems(problem_id);

CREATE TABLE IF NOT EXISTS contest_registrations (
  contest_id    INTEGER NOT NULL REFERENCES contests(id) ON DELETE CASCADE,
  user_id       INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (contest_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_contest_registrations_user ON contest_registrations(user_id);

CREATE TABLE IF NOT EXISTS contest_participations (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contest_id        INTEGER NOT NULL REFERENCES contests(id) ON DELETE CASCADE,
  user_id           INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  started_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  is_virtual        BOOLEAN NOT NULL DEFAULT false,
  personal_deadline TIMESTAMPTZ NOT NULL
);
-- Live participations are unique per (contest, user); virtual ones are not
-- (a user could do multiple virtual attempts). Enforced via partial unique index.
CREATE UNIQUE INDEX IF NOT EXISTS uniq_contest_live_participation
  ON contest_participations(contest_id, user_id) WHERE is_virtual = false;
CREATE INDEX IF NOT EXISTS idx_contest_participations_user ON contest_participations(user_id);
CREATE INDEX IF NOT EXISTS idx_contest_participations_contest ON contest_participations(contest_id);

CREATE TABLE IF NOT EXISTS contest_submissions (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  participation_id  INTEGER NOT NULL REFERENCES contest_participations(id) ON DELETE CASCADE,
  problem_id        INTEGER NOT NULL REFERENCES problems(id) ON DELETE CASCADE,
  submission_id     INTEGER NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_contest_submissions_participation ON contest_submissions(participation_id);
CREATE INDEX IF NOT EXISTS idx_contest_submissions_problem ON contest_submissions(problem_id);
CREATE INDEX IF NOT EXISTS idx_contest_submissions_submission ON contest_submissions(submission_id);

CREATE TABLE IF NOT EXISTS contest_ratings (
  user_id          INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE UNIQUE,
  rating           REAL NOT NULL DEFAULT 1500,
  rating_deviation REAL NOT NULL DEFAULT 350,
  volatility       REAL NOT NULL DEFAULT 0.06,
  contests_played  INTEGER NOT NULL DEFAULT 0,
  last_contest_at  TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS contest_rating_changes (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contest_id  INTEGER NOT NULL REFERENCES contests(id) ON DELETE CASCADE,
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  old_rating  REAL NOT NULL,
  new_rating  REAL NOT NULL,
  old_rd      REAL NOT NULL,
  new_rd      REAL NOT NULL,
  rank        INTEGER NOT NULL,
  delta       REAL NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_contest_rating_changes_user ON contest_rating_changes(user_id);
CREATE INDEX IF NOT EXISTS idx_contest_rating_changes_contest ON contest_rating_changes(contest_id);
